version: "3.7"

services:
  nft-marketplace-redis:
    image: redis:alpine
    container_name: nft-marketplace-redis
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - nft-marketplace
    ports:
      - "6379:6379"
    volumes:
      - "nft-marketplace-redis:/var/lib/redis"
      - "nft-marketplace-redis:/usr/local/etc/redis/redis.conf"
    restart: unless-stopped

  nft-marketplace-redis-web:
    image: rediscommander/redis-commander:latest
    container_name: nft-marketplace-redis-web
    environment:
      - REDIS_HOSTS=local:nft-marketplace-redis:6379
    networks:
      - nft-marketplace
    ports:
      - "9060:8081"
    depends_on:
      - nft-marketplace-redis
    restart: unless-stopped

  nft-marketplace-mongo:
    image: mongo:latest
    container_name: nft-marketplace-mongo
    environment:
      - MONGO_INITDB_DATABASE=app
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - nft-marketplace
    ports:
      - "27017:27017"
    volumes:
      - "nft-marketplace-mongo:/data/db:delegated"
    restart: unless-stopped

  nft-marketplace-mongo-web:
    image: mongo-express:latest
    container_name: nft-marketplace-mongo-web
    environment:
      - ME_CONFIG_MONGODB_SERVER=nft-marketplace-mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    networks:
      - nft-marketplace
    ports:
      - "9070:8081"
    depends_on:
      - nft-marketplace-mongo
    restart: unless-stopped

#  nft-marketplace-server:
#    build:
#      context: .
#    container_name: nft-marketplace-server
#    env_file: .env
#    networks:
#      - nft-marketplace
#    ports:
#      - "9080:9080"
#    volumes:
#      - "./src:/app/nft-marketplace/src:cached"
#    depends_on:
#      - nft-marketplace-redis
#      - nft-marketplace-mongo
#    restart: unless-stopped

volumes:
  nft-marketplace-mongo:
  nft-marketplace-redis:

networks:
  nft-marketplace:
